config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :authors
  

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    def name
        first_name + ' ' + last_name
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    def index
        @authors = Author.all
    end
    
    def show 
        @author = Author.find(params[:id])
    end
    
    def new
    end

    def create
        @author = Author.new(author_params)
        @author.save
        redirect_to root_path, notice: 'Success!'
    end

    private
        def author_params
            params.require(:author).permit(:first_name, :last_name, :homepage)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/index.html.erb
<h1>Listing Authors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Homepage</th>
    <th></th>
  </tr>

  <% @authors.each do |author| %>
    <tr>
      <td><%= author.name %></td>
      <td><%= author.homepage %></td>
      <td><%= link_to 'Show', author_path(author) %></td>
      <td><%= link_to 'Edit', edit_author_path(author) %></td>
    </tr>
  <% end %>
  <%= link_to 'New Author', new_author_path%>


</table>

app/views/authors/new.html.erb
<h1>New Author</h1>


<%= form_with scope: :author, url: authors_path, local: true do |form| %>
    <p>
      <%= form.label :first_name %><br>
      <%= form.text_field :first_name %>
    </p>
   
    <p>
      <%= form.label :last_name %><br>
      <%= form.text_field :last_name %>
    </p>

    <p>
      <%= form.label :homepage %><br>
      <%= form.text_field :homepage %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/authors/show.html.erb
<p>
    <strong>Name:</strong>
    <%= @author.name%>
</p>
<p>
    <strong>Homepage:</strong>
    <%= @author.homepage%>
</p>
<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', author_path %>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<h1>It works!</h1>
You are seeing the rendered view of Paper Management System 'views/home/index.html.erb'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails Intro Exercise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>